### PR TITLE
Milestone #4 -Game Instructions

### PR DESCRIPTION
**Pull request by Elukoye**
Added game instructions, kindly review

### CODE REVIEW

**Comment by Elukoye** [comment]
Kindly review

**Review by bellom — CHANGES_REQUESTED** [review]
Hi Team, 
**_Kindly be aware that adding `linter` is one of the Minimum Requirements Checklist for a project to be approved._**
**Just two things to work on;** 
1. **kindly add the linter and fix all errors if need too, checkout this [link](https://github.com/microverseinc/linters-config#troubleshooting) for help.**
example below;

image

2. Your `README` file only describe how the game works, it should also include steps to follow for a user to start playing the game, authors, and technologies used. Example; like the `github` link to `git clone` and all.

_Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you_

**Comment by Elukoye** [comment]
According to the milestone ,it says that we state the rules of the game
....maybe you could ask them to be more descriptive next time with the
milestones.

**Comment by Elukoye** [comment]
Then another question is why do we meet to set up code linters if there is
no file that contains code ?

**Comment by Elukoye** [comment]
Changes made, kindly review

**Comment by bellom** [comment]
Well, i forget to add `my opinion` to the comment, left to you to add more descriptive `README` or not.

For the linter, why :slightly_smiling_face: - well there is no need to debug simple mistakes like typos in the README file - the linter does it for you.

The best way to start a project is by adding the linter before you start to write any code, if there is no code in the branch, that will make it easier then. :+1: 
Note: Had it been it was added in your preview milestones, i might ignore but you guys shouldn't be running away from this....we are all here to learn, if you need help, message me on slack.

**Review by maelfosso — APPROVED** [review]
# Good job :+1: 

You can merge it.
Good luck with the next step.

**Comment by Elukoye** [comment]
Cool Ok thanks

**Pull request merged**
