### PR TITLE
commits for the milestone 2 please review

### PR DESCRIPTION
**Pull request by IBUNHABIBU**

### CODE REVIEW

**Review by bellom — CHANGES_REQUESTED** [review]
Hi Team, 
Good job working with `Git Flow` but guys you only wrote pseudo-code.
According to the pathwright we have the following steps;
1. Suggested branch name: user_interface. :heavy_check_mark: 
2. Display prompts for users, collect user input and only mock the logic (implementing the logic will be the next step). :negative_squared_cross_mark: 
3. Add executable file named main.rb to bin directory. This file should be responsible for user interaction. This is the only one place where puts and get.chomp can be used. :negative_squared_cross_mark: 

**.kindly add the linter and fix all errors if need too, checkout this [link](https://github.com/microverseinc/linters-config#troubleshooting) for help.**
example below;

image

_Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you_

**Comment by Elukoye** [comment]
Hi bellom,
I have tried understanding what milestone te o means ...
Please explain clearly what should go into that branch. Because one TSE
said that no code should be in the user -interface ...jist how you are
going to implement the game logic.
Thanks in Advance.

**Comment by Elukoye** [comment]
Also step three is there ,we do have a bin directory with a main.rb file.

**Comment by bellom** [comment]
1. Well, maybe you didn't understand the TSE comment, you are to write some code that will take input from the user and select a symbol, for now you can just mock the `logic` that happens after. For example; when the game starts, an user needs to insert their player name and select their symbol.

2. Yes, you have the `main.rb` file, which has nothing like( puts and get.chomp ) - so half of step 3 is there :smile: 

I hope it all clear now :slightly_smiling_face:

**Comment by Elukoye** [comment]
Corrected

**Comment by bellom** [comment]
## reviewing this project

**Review by bellom — CHANGES_REQUESTED** [review]
Hi Team, 
Great work making half of the necessary corrections from the previous review, just the `linter` installation left, kindly work on it.....checkout the link from my first review.

kindly re-submit for review.....

**Comment by Elukoye** [comment]
Hi, I confirmed twice, this branch has both stickler and rubocop set up as code linters. Or u meant another linter?

**Review by bolah2009 — APPROVED** [review]
# Awesome Job Team :clap: 

Let's merge (Milestone #1 Project Setup) first before merging this (PR) to `develop` branch. :+1: 

### Please [resolve all merge conflicts](https://help.github.com/en/articles/resolving-a-merge-conflict-on-github). 

:bulb: HINT: After merging a milestone. Sync ([**merge**](https://git-scm.com/docs/git-merge)) updated `develop` branch with the current branch you working on.

Good luck with your next milestone. :star2: 

Cheers
[Bola](https://bolabuari.com/)

###### PS: Note that comments tagged as `OPTIONAL` are not part of the minimum requirements to approve this PR

**Pull request merged**
